require('core.plugin_config.bufferline')
require('core.plugin_config.colorscheme')
require('core.plugin_config.lualine')
-- require('core.plugin_config.nvimtree_config')
require('core.plugin_config.neotree')
require('core.plugin_config.treesitter')
require('core.plugin_config.oil')
require('core.plugin_config.telescope')
require('core.plugin_config.nvimsurround')
require('core.plugin_config.gitsigns')
